### ISSUE TITLE
عدم نمایش آیکون ها

### ISSUE THREAD

**Issue by ehsan58** [sibche2013/WhmcsThemeRTL#1]
سلام خسته نباشید  در قدم اول واقعا سپاسگذارم بابت زحمات و انتشار قالب 
اما آیکون های استفاده شده در قالب کلا نمایش داده نمیشه  
https://i.postimg.cc/m217ySqT/Capture.png

**Comment by sibche2013** [comment]
> سلام خسته نباشید در قدم اول واقعا سپاسگذارم بابت زحمات و انتشار قالب
> اما آیکون های استفاده شده در قالب کلا نمایش داده نمیشه
> https://i.postimg.cc/m217ySqT/Capture.png

این مشکل فونت باشه فکر کنم ، اگر میتونید در تلگرام با آیدی
@sibche2013 
در تماس باشید تا سایتتون رو بدین و بررسی کنم و مشکل حل بشه

**Comment by sibche2013** [comment]
> > سلام خسته نباشید در قدم اول واقعا سپاسگذارم بابت زحمات و انتشار قالب
> > اما آیکون های استفاده شده در قالب کلا نمایش داده نمیشه
> > https://i.postimg.cc/m217ySqT/Capture.png
> 
> این مشکل فونت باشه فکر کنم ، اگر میتونید در تلگرام با آیدی
> @sibche2013
> در تماس باشید تا سایتتون رو بدین و بررسی کنم و مشکل حل بشه

مشکل از نبود
font awesome 
بود
که فونت رو باید در 
includes>>head.tpl
لود کنید
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">`
میتونید از همین cdn استفاده کنید یا فونتو دانلود و در هاستتون بارگزاری و استفاده کنید
